# Elasticsearch Configuration for ReachInbox Onebox
cluster.name: reachinbox-cluster
node.name: reachinbox-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings
discovery.type: single-node

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Memory settings
bootstrap.memory_lock: true

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Logging
logger.level: INFO

# Performance settings
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 10%

# Email-specific settings
index.max_result_window: 50000
index.max_inner_result_window: 1000
