version: '3.8'

services:
  # Elasticsearch for Full-Text Search and Email Storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: reachinbox-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - cluster.name=reachinbox-cluster
      - node.name=reachinbox-node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # Qdrant Vector Database for RAG and Embeddings
  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: reachinbox-qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_REQUESTS=100
      - QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS=4
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant/config:/qdrant/config:ro
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Redis for Caching and Session Management
  redis:
    image: redis:7.2-alpine
    container_name: reachinbox-redis
    command: redis-server --appendonly yes --requirepass reachinbox_redis_2024
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - reachinbox-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: reachinbox-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elasticsearch
      - qdrant
    networks:
      - reachinbox-network
    restart: unless-stopped

  # Elasticsearch Head for Management (Development Only)
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    container_name: reachinbox-elasticsearch-head
    ports:
      - "9100:9100"
    depends_on:
      - elasticsearch
    networks:
      - reachinbox-network
    restart: unless-stopped
    profiles:
      - dev

volumes:
  elasticsearch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/elasticsearch
  qdrant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/qdrant
  redis_data:
    driver: local

networks:
  reachinbox-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16